# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiLayout.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(935, 751)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(12, 12, 911, 531))
        self.frame.setMinimumSize(QtCore.QSize(911, 531))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame_3 = QtGui.QFrame(self.frame)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.formLayout = QtGui.QFormLayout(self.frame_3)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.Step1Label = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Step1Label.setFont(font)
        self.Step1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Step1Label.setObjectName(_fromUtf8("Step1Label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.Step1Label)
        self.ResourceField = QtGui.QLineEdit(self.frame_3)
        self.ResourceField.setStatusTip(_fromUtf8(""))
        self.ResourceField.setText(_fromUtf8(""))
        self.ResourceField.setObjectName(_fromUtf8("ResourceField"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.ResourceField)
        self.CollectModeLabel = QtGui.QLabel(self.frame_3)
        self.CollectModeLabel.setObjectName(_fromUtf8("CollectModeLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.CollectModeLabel)
        self.CollectmodeSBtn = QtGui.QRadioButton(self.frame_3)
        self.CollectmodeSBtn.setObjectName(_fromUtf8("CollectmodeSBtn"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.CollectmodeSBtn)
        self.CollectmodeTBtn = QtGui.QRadioButton(self.frame_3)
        self.CollectmodeTBtn.setObjectName(_fromUtf8("CollectmodeTBtn"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.CollectmodeTBtn)
        self.Languagelabel = QtGui.QLabel(self.frame_3)
        self.Languagelabel.setObjectName(_fromUtf8("Languagelabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.Languagelabel)
        self.ExploreBtn = QtGui.QPushButton(self.frame_3)
        self.ExploreBtn.setObjectName(_fromUtf8("ExploreBtn"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.SpanningRole, self.ExploreBtn)
        self.line = QtGui.QFrame(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line.setFont(font)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.SpanningRole, self.line)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.formLayout.setItem(8, QtGui.QFormLayout.SpanningRole, spacerItem)
        self.Step2Label = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Step2Label.setFont(font)
        self.Step2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Step2Label.setObjectName(_fromUtf8("Step2Label"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.SpanningRole, self.Step2Label)
        self.Step2Infolabel = QtGui.QLabel(self.frame_3)
        self.Step2Infolabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Step2Infolabel.setWordWrap(False)
        self.Step2Infolabel.setObjectName(_fromUtf8("Step2Infolabel"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.SpanningRole, self.Step2Infolabel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.formLayout.setItem(11, QtGui.QFormLayout.SpanningRole, spacerItem1)
        self.line_2 = QtGui.QFrame(self.frame_3)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.SpanningRole, self.line_2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.formLayout.setItem(13, QtGui.QFormLayout.SpanningRole, spacerItem2)
        self.Step3Label = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Step3Label.setFont(font)
        self.Step3Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Step3Label.setObjectName(_fromUtf8("Step3Label"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.SpanningRole, self.Step3Label)
        self.ExtractBtn = QtGui.QPushButton(self.frame_3)
        self.ExtractBtn.setObjectName(_fromUtf8("ExtractBtn"))
        self.formLayout.setWidget(15, QtGui.QFormLayout.SpanningRole, self.ExtractBtn)
        self.progressBar = QtGui.QProgressBar(self.frame_3)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.formLayout.setWidget(16, QtGui.QFormLayout.SpanningRole, self.progressBar)
        self.progressBar_2 = QtGui.QProgressBar(self.frame_3)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.SpanningRole, self.progressBar_2)
        self.LanguageCombo = QtGui.QComboBox(self.frame_3)
        self.LanguageCombo.setObjectName(_fromUtf8("LanguageCombo"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.LanguageCombo)
        self.ResourceLabel = QtGui.QLabel(self.frame_3)
        self.ResourceLabel.setObjectName(_fromUtf8("ResourceLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.ResourceLabel)
        self.horizontalLayout.addWidget(self.frame_3)
        self.textEdit = QtGui.QTextEdit(self.frame)
        self.textEdit.setMinimumSize(QtCore.QSize(600, 465))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.horizontalLayout.addWidget(self.textEdit, 0, QtCore.Qt.AlignRight)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(12, 550, 911, 170))
        self.frame_2.setMinimumSize(QtCore.QSize(911, 170))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(2, 5, 907, 191))
        self.label.setMinimumSize(QtCore.QSize(907, 190))
        self.label.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(33, 255, 6);"))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 935, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.Step1Label.setText(_translate("MainWindow", "STEP 1", None))
        self.ResourceField.setToolTip(_translate("MainWindow", "Enter the Resource/Domain name for which the triples should be extracted.\n"
"\n"
"For eg., \"Kobe_Bryant\", \"William_Gibson\" for single resources.\n"
"              \"BasketballPlayer\", \"Writer\" for group of resources.", None))
        self.CollectModeLabel.setText(_translate("MainWindow", "Collect Mode :", None))
        self.CollectmodeSBtn.setToolTip(_translate("MainWindow", "Select if it is a single resource", None))
        self.CollectmodeSBtn.setText(_translate("MainWindow", "Single", None))
        self.CollectmodeTBtn.setToolTip(_translate("MainWindow", "Select if it is a group of resources", None))
        self.CollectmodeTBtn.setText(_translate("MainWindow", "Topic/Domain", None))
        self.Languagelabel.setText(_translate("MainWindow", "Language :", None))
        self.ExploreBtn.setText(_translate("MainWindow", "Explore", None))
        self.Step2Label.setText(_translate("MainWindow", "STEP 2", None))
        self.Step2Infolabel.setText(_translate("MainWindow", "Add/Edit ontology mappings as \n"
"required in the edit box right side.", None))
        self.Step3Label.setText(_translate("MainWindow", "STEP 3", None))
        self.ExtractBtn.setText(_translate("MainWindow", "Extract Triples", None))
        self.LanguageCombo.setToolTip(_translate("MainWindow", "Enter Language of wiki pages", None))
        self.ResourceLabel.setText(_translate("MainWindow", "Resource :", None))
        self.label.setText(_translate("MainWindow", ">>", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

