# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiLayout.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 775)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(self.tab)
        self.frame_3.setMaximumSize(QtCore.QSize(300, 510))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.formLayout = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout.setObjectName("formLayout")
        self.Step1Label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Step1Label.setFont(font)
        self.Step1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Step1Label.setObjectName("Step1Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.Step1Label)
        self.ResourceLabel = QtWidgets.QLabel(self.frame_3)
        self.ResourceLabel.setObjectName("ResourceLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ResourceLabel)
        self.ResourceField = QtWidgets.QLineEdit(self.frame_3)
        self.ResourceField.setStatusTip("")
        self.ResourceField.setText("")
        self.ResourceField.setObjectName("ResourceField")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ResourceField)
        self.CollectModeLabel = QtWidgets.QLabel(self.frame_3)
        self.CollectModeLabel.setObjectName("CollectModeLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.CollectModeLabel)
        self.CollectmodeSBtn = QtWidgets.QRadioButton(self.frame_3)
        self.CollectmodeSBtn.setChecked(True)
        self.CollectmodeSBtn.setObjectName("CollectmodeSBtn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.CollectmodeSBtn)
        self.CollectmodeTBtn = QtWidgets.QRadioButton(self.frame_3)
        self.CollectmodeTBtn.setObjectName("CollectmodeTBtn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.CollectmodeTBtn)
        self.Languagelabel = QtWidgets.QLabel(self.frame_3)
        self.Languagelabel.setObjectName("Languagelabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Languagelabel)
        self.LanguageCombo = QtWidgets.QComboBox(self.frame_3)
        self.LanguageCombo.setObjectName("LanguageCombo")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LanguageCombo)
        self.extractLabel = QtWidgets.QLabel(self.frame_3)
        self.extractLabel.setObjectName("extractLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.extractLabel)
        self.listsCheckBox = QtWidgets.QCheckBox(self.frame_3)
        self.listsCheckBox.setChecked(True)
        self.listsCheckBox.setObjectName("listsCheckBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.listsCheckBox)
        self.tablesCheckBox = QtWidgets.QCheckBox(self.frame_3)
        self.tablesCheckBox.setChecked(True)
        self.tablesCheckBox.setObjectName("tablesCheckBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.tablesCheckBox)
        self.ExploreDomainMessageLabel = QtWidgets.QLabel(self.frame_3)
        self.ExploreDomainMessageLabel.setText("")
        self.ExploreDomainMessageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ExploreDomainMessageLabel.setObjectName("ExploreDomainMessageLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.ExploreDomainMessageLabel)
        self.ExploreBtn = QtWidgets.QPushButton(self.frame_3)
        self.ExploreBtn.setObjectName("ExploreBtn")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.ExploreBtn)
        self.line = QtWidgets.QFrame(self.frame_3)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.line)
        self.Step2Label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Step2Label.setFont(font)
        self.Step2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Step2Label.setObjectName("Step2Label")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.SpanningRole, self.Step2Label)
        self.Step2Infolabel = QtWidgets.QLabel(self.frame_3)
        self.Step2Infolabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Step2Infolabel.setWordWrap(False)
        self.Step2Infolabel.setObjectName("Step2Infolabel")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.SpanningRole, self.Step2Infolabel)
        self.saveBtn = QtWidgets.QPushButton(self.frame_3)
        self.saveBtn.setObjectName("saveBtn")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.SpanningRole, self.saveBtn)
        self.line_2 = QtWidgets.QFrame(self.frame_3)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.SpanningRole, self.line_2)
        self.Step3Label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Step3Label.setFont(font)
        self.Step3Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Step3Label.setObjectName("Step3Label")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.SpanningRole, self.Step3Label)
        self.ExtractBtn = QtWidgets.QPushButton(self.frame_3)
        self.ExtractBtn.setObjectName("ExtractBtn")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.SpanningRole, self.ExtractBtn)
        self.gridLayout.addWidget(self.frame_3, 0, 1, 1, 1)
        self.TerminalWindow = QtWidgets.QTextBrowser(self.tab)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(33, 255, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 255, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.TerminalWindow.setPalette(palette)
        self.TerminalWindow.setObjectName("TerminalWindow")
        self.gridLayout.addWidget(self.TerminalWindow, 1, 1, 1, 2)
        self.DomainSettingsTreeWidget = QtWidgets.QTreeWidget(self.tab)
        self.DomainSettingsTreeWidget.setObjectName("DomainSettingsTreeWidget")
        self.DomainSettingsTreeWidget.headerItem().setText(0, "1")
        self.gridLayout.addWidget(self.DomainSettingsTreeWidget, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_6 = QtWidgets.QFrame(self.tab_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_6)
        self.formLayout_2.setObjectName("formLayout_2")
        self.updateMapperLabel = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.updateMapperLabel.setFont(font)
        self.updateMapperLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.updateMapperLabel.setObjectName("updateMapperLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.updateMapperLabel)
        self.ListOfMappersLabel = QtWidgets.QLabel(self.frame_6)
        self.ListOfMappersLabel.setObjectName("ListOfMappersLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ListOfMappersLabel)
        self.ListOfMappersCombo = QtWidgets.QComboBox(self.frame_6)
        self.ListOfMappersCombo.setObjectName("ListOfMappersCombo")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ListOfMappersCombo)
        self.ShowMappersBtn = QtWidgets.QPushButton(self.frame_6)
        self.ShowMappersBtn.setObjectName("ShowMappersBtn")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ShowMappersBtn)
        self.MapperNameLabel = QtWidgets.QLabel(self.frame_6)
        self.MapperNameLabel.setObjectName("MapperNameLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.MapperNameLabel)
        self.ListSectionsLabel = QtWidgets.QLabel(self.frame_6)
        self.ListSectionsLabel.setObjectName("ListSectionsLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.ListSectionsLabel)
        self.ListHeadersTextEdit = QtWidgets.QTextEdit(self.frame_6)
        self.ListHeadersTextEdit.setObjectName("ListHeadersTextEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ListHeadersTextEdit)
        self.TableHeadersLabel = QtWidgets.QLabel(self.frame_6)
        self.TableHeadersLabel.setObjectName("TableHeadersLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.TableHeadersLabel)
        self.TableSectionsTextEdit = QtWidgets.QTextEdit(self.frame_6)
        self.TableSectionsTextEdit.setObjectName("TableSectionsTextEdit")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.TableSectionsTextEdit)
        self.frame_11 = QtWidgets.QFrame(self.frame_6)
        font = QtGui.QFont()
        font.setKerning(True)
        self.frame_11.setFont(font)
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setMidLineWidth(-2)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ExtractorsLabel = QtWidgets.QLabel(self.frame_11)
        self.ExtractorsLabel.setToolTip("")
        self.ExtractorsLabel.setObjectName("ExtractorsLabel")
        self.horizontalLayout_3.addWidget(self.ExtractorsLabel)
        self.extractor_checkBox_1 = QtWidgets.QCheckBox(self.frame_11)
        self.extractor_checkBox_1.setObjectName("extractor_checkBox_1")
        self.horizontalLayout_3.addWidget(self.extractor_checkBox_1)
        self.extractor_checkBox_2 = QtWidgets.QCheckBox(self.frame_11)
        self.extractor_checkBox_2.setObjectName("extractor_checkBox_2")
        self.horizontalLayout_3.addWidget(self.extractor_checkBox_2)
        self.extractor_checkBox_3 = QtWidgets.QCheckBox(self.frame_11)
        self.extractor_checkBox_3.setObjectName("extractor_checkBox_3")
        self.horizontalLayout_3.addWidget(self.extractor_checkBox_3)
        self.extractor_checkBox_4 = QtWidgets.QCheckBox(self.frame_11)
        self.extractor_checkBox_4.setObjectName("extractor_checkBox_4")
        self.horizontalLayout_3.addWidget(self.extractor_checkBox_4)
        self.extractor_checkBox_5 = QtWidgets.QCheckBox(self.frame_11)
        self.extractor_checkBox_5.setObjectName("extractor_checkBox_5")
        self.horizontalLayout_3.addWidget(self.extractor_checkBox_5)
        self.extractor_checkBox_6 = QtWidgets.QCheckBox(self.frame_11)
        self.extractor_checkBox_6.setObjectName("extractor_checkBox_6")
        self.horizontalLayout_3.addWidget(self.extractor_checkBox_6)
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.frame_11)
        self.frame_10 = QtWidgets.QFrame(self.frame_6)
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.YearsLabel = QtWidgets.QLabel(self.frame_10)
        self.YearsLabel.setObjectName("YearsLabel")
        self.horizontalLayout_2.addWidget(self.YearsLabel)
        self.YearsYesRadio = QtWidgets.QRadioButton(self.frame_10)
        self.YearsYesRadio.setObjectName("YearsYesRadio")
        self.horizontalLayout_2.addWidget(self.YearsYesRadio)
        self.YearsNoRadio = QtWidgets.QRadioButton(self.frame_10)
        self.YearsNoRadio.setObjectName("YearsNoRadio")
        self.horizontalLayout_2.addWidget(self.YearsNoRadio)
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.frame_10)
        self.OntologyLabel = QtWidgets.QLabel(self.frame_6)
        self.OntologyLabel.setObjectName("OntologyLabel")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.OntologyLabel)
        self.OntologyTextEdit = QtWidgets.QTextEdit(self.frame_6)
        self.OntologyTextEdit.setObjectName("OntologyTextEdit")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.OntologyTextEdit)
        self.SaveMapperBtn = QtWidgets.QPushButton(self.frame_6)
        self.SaveMapperBtn.setObjectName("SaveMapperBtn")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.SaveMapperBtn)
        self.MapperNameLineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.MapperNameLineEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.MapperNameLineEdit.setObjectName("MapperNameLineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.MapperNameLineEdit)
        self.UpdateMapperMessageLabel = QtWidgets.QLabel(self.frame_6)
        self.UpdateMapperMessageLabel.setText("")
        self.UpdateMapperMessageLabel.setObjectName("UpdateMapperMessageLabel")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.UpdateMapperMessageLabel)
        self.horizontalLayout.addWidget(self.frame_6)
        self.frame_4 = QtWidgets.QFrame(self.tab_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.formLayout_3 = QtWidgets.QFormLayout(self.frame_4)
        self.formLayout_3.setObjectName("formLayout_3")
        self.UpdateDomainLabel = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.UpdateDomainLabel.setFont(font)
        self.UpdateDomainLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.UpdateDomainLabel.setObjectName("UpdateDomainLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.UpdateDomainLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_3.setItem(1, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.DomainsListLabel = QtWidgets.QLabel(self.frame_4)
        self.DomainsListLabel.setObjectName("DomainsListLabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.DomainsListLabel)
        self.DomainsListCombo = QtWidgets.QComboBox(self.frame_4)
        self.DomainsListCombo.setObjectName("DomainsListCombo")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.DomainsListCombo)
        self.ShowDomainBtn = QtWidgets.QPushButton(self.frame_4)
        self.ShowDomainBtn.setObjectName("ShowDomainBtn")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ShowDomainBtn)
        self.DomainNameLabel = QtWidgets.QLabel(self.frame_4)
        self.DomainNameLabel.setObjectName("DomainNameLabel")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.DomainNameLabel)
        self.DomainNameLineEdit = QtWidgets.QLineEdit(self.frame_4)
        self.DomainNameLineEdit.setObjectName("DomainNameLineEdit")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.DomainNameLineEdit)
        self.AddDomainMappersLabel = QtWidgets.QLabel(self.frame_4)
        self.AddDomainMappersLabel.setObjectName("AddDomainMappersLabel")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.AddDomainMappersLabel)
        self.MappersListView = QtWidgets.QListView(self.frame_4)
        self.MappersListView.setObjectName("MappersListView")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.MappersListView)
        self.SaveDomainBtn = QtWidgets.QPushButton(self.frame_4)
        self.SaveDomainBtn.setObjectName("SaveDomainBtn")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.SaveDomainBtn)
        self.line_3 = QtWidgets.QFrame(self.frame_4)
        self.line_3.setMinimumSize(QtCore.QSize(50, 20))
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.line_3)
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.SpanningRole, self.label_10)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_3.setItem(12, QtWidgets.QFormLayout.SpanningRole, spacerItem1)
        self.CheckOntologyLabel = QtWidgets.QLabel(self.frame_4)
        self.CheckOntologyLabel.setObjectName("CheckOntologyLabel")
        self.formLayout_3.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.CheckOntologyLabel)
        self.CheckOntologyField = QtWidgets.QLineEdit(self.frame_4)
        self.CheckOntologyField.setObjectName("CheckOntologyField")
        self.formLayout_3.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.CheckOntologyField)
        self.CheckBtn = QtWidgets.QPushButton(self.frame_4)
        self.CheckBtn.setObjectName("CheckBtn")
        self.formLayout_3.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.CheckBtn)
        self.ResultLabel = QtWidgets.QLabel(self.frame_4)
        self.ResultLabel.setObjectName("ResultLabel")
        self.formLayout_3.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.ResultLabel)
        self.CheckOntologyLanguageCombo = QtWidgets.QComboBox(self.frame_4)
        self.CheckOntologyLanguageCombo.setObjectName("CheckOntologyLanguageCombo")
        self.formLayout_3.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.CheckOntologyLanguageCombo)
        self.CheckOntologyLanguageLabel = QtWidgets.QLabel(self.frame_4)
        self.CheckOntologyLanguageLabel.setObjectName("CheckOntologyLanguageLabel")
        self.formLayout_3.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.CheckOntologyLanguageLabel)
        self.CheckOntologyResult = QtWidgets.QLabel(self.frame_4)
        self.CheckOntologyResult.setText("")
        self.CheckOntologyResult.setObjectName("CheckOntologyResult")
        self.formLayout_3.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.CheckOntologyResult)
        self.UpdateDomainMessageLabel = QtWidgets.QLabel(self.frame_4)
        self.UpdateDomainMessageLabel.setText("")
        self.UpdateDomainMessageLabel.setObjectName("UpdateDomainMessageLabel")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.UpdateDomainMessageLabel)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.tab_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.formLayout_4 = QtWidgets.QFormLayout(self.frame_5)
        self.formLayout_4.setObjectName("formLayout_4")
        self.ResourcesListLabel = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ResourcesListLabel.setFont(font)
        self.ResourcesListLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ResourcesListLabel.setObjectName("ResourcesListLabel")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.ResourcesListLabel)
        self.DomainLabel = QtWidgets.QLabel(self.frame_5)
        self.DomainLabel.setObjectName("DomainLabel")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.DomainLabel)
        self.DomainLineEdit = QtWidgets.QLineEdit(self.frame_5)
        self.DomainLineEdit.setObjectName("DomainLineEdit")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.DomainLineEdit)
        self.DomainLanguageLabel = QtWidgets.QLabel(self.frame_5)
        self.DomainLanguageLabel.setObjectName("DomainLanguageLabel")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.DomainLanguageLabel)
        self.ResoucesListView = QtWidgets.QListView(self.frame_5)
        self.ResoucesListView.setMinimumSize(QtCore.QSize(0, 500))
        self.ResoucesListView.setObjectName("ResoucesListView")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.ResoucesListView)
        self.ShowResourcesBtn = QtWidgets.QPushButton(self.frame_5)
        self.ShowResourcesBtn.setObjectName("ShowResourcesBtn")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ShowResourcesBtn)
        self.ResourcesListResult = QtWidgets.QLabel(self.frame_5)
        self.ResourcesListResult.setText("")
        self.ResourcesListResult.setObjectName("ResourcesListResult")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ResourcesListResult)
        self.DomainLanguageCombo = QtWidgets.QComboBox(self.frame_5)
        self.DomainLanguageCombo.setObjectName("DomainLanguageCombo")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.DomainLanguageCombo)
        self.horizontalLayout.addWidget(self.frame_5)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_4.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tablist-Extractor"))
        self.Step1Label.setText(_translate("MainWindow", "STEP 1"))
        self.ResourceLabel.setText(_translate("MainWindow", "Resource :"))
        self.ResourceField.setToolTip(_translate("MainWindow", "Enter the Resource/Domain name for which the triples should be extracted.\n"
"\n"
"For eg., \"Kobe_Bryant\", \"William_Gibson\" for single resources.\n"
"              \"BasketballPlayer\", \"Writer\" for group of resources."))
        self.CollectModeLabel.setText(_translate("MainWindow", "Collect Mode :"))
        self.CollectmodeSBtn.setToolTip(_translate("MainWindow", "Select if it is a single resource"))
        self.CollectmodeSBtn.setText(_translate("MainWindow", "Single"))
        self.CollectmodeTBtn.setToolTip(_translate("MainWindow", "Select if it is a group of resources"))
        self.CollectmodeTBtn.setText(_translate("MainWindow", "Topic/Domain"))
        self.Languagelabel.setText(_translate("MainWindow", "Language :"))
        self.LanguageCombo.setToolTip(_translate("MainWindow", "Enter Language of wiki pages"))
        self.extractLabel.setText(_translate("MainWindow", "Extract :"))
        self.listsCheckBox.setText(_translate("MainWindow", "Lists"))
        self.tablesCheckBox.setText(_translate("MainWindow", "Tables"))
        self.ExploreBtn.setText(_translate("MainWindow", "Explore"))
        self.Step2Label.setText(_translate("MainWindow", "STEP 2"))
        self.Step2Infolabel.setText(_translate("MainWindow", "Add/Edit ontology mappings as \n"
"required in the edit box right side.\n"
"After editing, click the \n"
"save button to update mappings."))
        self.saveBtn.setText(_translate("MainWindow", "Save"))
        self.Step3Label.setText(_translate("MainWindow", "STEP 3"))
        self.ExtractBtn.setText(_translate("MainWindow", "Extract Triples"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Extractor"))
        self.updateMapperLabel.setText(_translate("MainWindow", "Add/Edit Mappers"))
        self.ListOfMappersLabel.setText(_translate("MainWindow", "List of Mappers:"))
        self.ListOfMappersCombo.setToolTip(_translate("MainWindow", "Select from list of available mappers."))
        self.ShowMappersBtn.setText(_translate("MainWindow", "Show"))
        self.MapperNameLabel.setText(_translate("MainWindow", "Mapper Name:"))
        self.ListSectionsLabel.setText(_translate("MainWindow", "List Headers:"))
        self.ListHeadersTextEdit.setToolTip(_translate("MainWindow", "Contains list of headers with its associated language.\n"
"These headers are searched in the wiki page, for extracting list elements.\n"
"\n"
"Follow the structure as shown\n"
"Format:\n"
"{\n"
"    \"language1\" : [ , , ],\n"
"    \"language2\" : [ , , ],\n"
"     ..\n"
"}\n"
""))
        self.TableHeadersLabel.setText(_translate("MainWindow", "Table Sections:"))
        self.TableSectionsTextEdit.setToolTip(_translate("MainWindow", "Contains list of sections with its associated language.\n"
"These table sections are searched in the wiki page, for extracting table elements.\n"
"\n"
"Follow the structure as shown\n"
"Format:\n"
"{\n"
"    \"language1\" : [ , , ],\n"
"    \"language2\" : [ , , ],\n"
"     ..\n"
"}\n"
""))
        self.ExtractorsLabel.setText(_translate("MainWindow", "Extractors:"))
        self.extractor_checkBox_1.setToolTip(_translate("MainWindow", "Italic Mapper"))
        self.extractor_checkBox_1.setText(_translate("MainWindow", "1"))
        self.extractor_checkBox_2.setToolTip(_translate("MainWindow", "Reference Mapper"))
        self.extractor_checkBox_2.setText(_translate("MainWindow", "2"))
        self.extractor_checkBox_3.setToolTip(_translate("MainWindow", "Quote Mapper"))
        self.extractor_checkBox_3.setText(_translate("MainWindow", "3"))
        self.extractor_checkBox_4.setToolTip(_translate("MainWindow", "General Mapper"))
        self.extractor_checkBox_4.setText(_translate("MainWindow", "4"))
        self.extractor_checkBox_5.setToolTip(_translate("MainWindow", "isbn Mapper"))
        self.extractor_checkBox_5.setText(_translate("MainWindow", "5"))
        self.extractor_checkBox_6.setToolTip(_translate("MainWindow", "Alumni Profession Mapper"))
        self.extractor_checkBox_6.setText(_translate("MainWindow", "6"))
        self.YearsLabel.setText(_translate("MainWindow", "Includes Years:"))
        self.YearsYesRadio.setText(_translate("MainWindow", "Yes"))
        self.YearsNoRadio.setText(_translate("MainWindow", "No"))
        self.OntologyLabel.setText(_translate("MainWindow", "Ontology:"))
        self.OntologyTextEdit.setToolTip(_translate("MainWindow", "Contains dictionary of ontologies with its associated language.\n"
"\n"
"Follow the structure as shown\n"
"Format:\n"
"{\n"
"    \"language1\" : [ \"key\" : \"Ontology\",\n"
"                               , ..  ],\n"
"    \"language2\" : [ \"key\" : \"Ontology\",\n"
"                               , ..  ],\n"
"     ..\n"
"}\n"
""))
        self.SaveMapperBtn.setText(_translate("MainWindow", "Save"))
        self.MapperNameLineEdit.setToolTip(_translate("MainWindow", "Name of the mapper"))
        self.frame_4.setToolTip(_translate("MainWindow", "Select a Domain"))
        self.UpdateDomainLabel.setText(_translate("MainWindow", "Add/Edit Domain"))
        self.DomainsListLabel.setText(_translate("MainWindow", "Domains:"))
        self.ShowDomainBtn.setText(_translate("MainWindow", "Show"))
        self.DomainNameLabel.setText(_translate("MainWindow", "Domain:"))
        self.DomainNameLineEdit.setToolTip(_translate("MainWindow", "Domain Name"))
        self.AddDomainMappersLabel.setText(_translate("MainWindow", "Mappers:"))
        self.MappersListView.setToolTip(_translate("MainWindow", "List of mappers associated with the domain.\n"
"Do not change the format."))
        self.SaveDomainBtn.setText(_translate("MainWindow", "Save"))
        self.label_10.setText(_translate("MainWindow", "Check Existence of Ontology"))
        self.CheckOntologyLabel.setText(_translate("MainWindow", "Ontology:"))
        self.CheckBtn.setText(_translate("MainWindow", "Check"))
        self.ResultLabel.setText(_translate("MainWindow", "Result:"))
        self.CheckOntologyLanguageCombo.setToolTip(_translate("MainWindow", "Enter Language of wiki pages"))
        self.CheckOntologyLanguageLabel.setText(_translate("MainWindow", "Language :"))
        self.ResourcesListLabel.setText(_translate("MainWindow", "List of Resources in a Domain"))
        self.DomainLabel.setText(_translate("MainWindow", "Domain:"))
        self.DomainLineEdit.setToolTip(_translate("MainWindow", "Get list of associated resources in a specific domain.\n"
"\n"
"Eg., Writer, BasketballPlayer etc."))
        self.DomainLanguageLabel.setText(_translate("MainWindow", "Language :"))
        self.ShowResourcesBtn.setText(_translate("MainWindow", "Show Resources"))
        self.DomainLanguageCombo.setToolTip(_translate("MainWindow", "Enter Language of wiki pages"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Utilities"))

